# Use the official Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all files from the current directory on the host to the container's /app directory
ADD . /app

# Install the required dependencies
# RUN pip install requests Beautifulsoup4

# Set the default command to execute your Python script
CMD ["python", "main.py"]
